version: "3"
services:
  # can be accessed in the same network
  # service name
  consul-imooc:
    # addr of image used
    image: cap1573/consul
    # map to host ports
    ports:
      - "8500:8500"
  jaeger-imooc:
    image: cap1573/jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"
  hystrix-dashboard:
    image: cap1573/hystrix-dashboard
    ports:
      - "9002:9002"

