global:
  scrape_interval:     15s
  external_labels:
    monitor: 'go-micro-monitor'
scrape_configs:
  - job_name: 'order'
    scrape_interval: 5s
    static_configs:
      - targets: ["146.169.152.43:9092"]
